FileVersion = 1

[Workspace]
StartupProject = "Sample"

[Projects]
Wasm4 = {Path = "."}
Sample = {Path = "Sample"}

[Configs.Debug.Wasm32]
PreprocessorMacros = ["BF_CRT_DISABLE"]
TargetTriple = "wasm32-unknown-unknown"
BfSIMDSetting = "None"
BfOptimizationLevel = "Og"
AllocType = "CRT"
RuntimeKind = "Disabled"
ReflectKind = "Minimal"
EnableObjectDebugFlags = false
IntermediateType = "ObjectAndIRCode"
